on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-22.04

    steps:
    - name: Print public key fingerprint
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 644 ~/.ssh/id_rsa.pub
        ssh-keygen -lf ~/.ssh/id_rsa.pub


    
    - name: install ssh keys
      run: |
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER }} > ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        # Debug: List loaded keys in the agent
        ssh-add -l
    - name: connect, pull, build, and restart
      run: ssh -v ${{ secrets.USERNAME }}@${{ secrets.SERVER }} "export PATH=\"/home/ubuntu/.nvm/versions/node/v18.16.0/bin:/home/ubuntu/.nvm/versions/node/v18.16.0/bin/yarn:\$PATH\" && cd /home/ubuntu/proposal-copilot && git fetch origin main && git reset --hard origin/main && git clean -f -d -x --exclude=.env --exclude=storage && git pull origin main --force && pip install -r requirements.txt && yarn install && yarn build && yarn build:js && sudo systemctl restart proposal-copilot.service && exit"


    - name: cleanup
      if: always()
      run: rm -rf ~/.ssh
